### ISSUE TITLE
读书 | 观影 | 追番 | 隐秀 | seriouszyx

### ISSUE THREAD

**Issue by seriouszyx** [seriouszyx/seriouszyx.github.io#22]
https://seriouszyx.github.io/reading/ 

 2019 年 读书（2） 《围城》(2.4) 突然很怕自己像方鸿渐一样，凭借着一点小聪明混到留洋博士，却没能踏实地学习知识，而是与鲍小姐之辈虚度青春；不喜欢爱自己的苏文纨，却爱上了不喜欢自己唐晓芙；与曾经的情敌赵辛楣成为挚友；受不了充满尔虞我诈的三闾大学，与略显平凡的孙柔嘉结婚，又因双方家庭等原因一怒之下分手。 最后想起饭局上的那句“爱情就像是一座围城，里面的人想出来，外面的人想进去”。   《我

**Comment by Dawn2019** [comment]
老哥，可以用豆瓣插件来添加图书/电影/游戏的哦，我是按那个插件搞得，你可以看一下效果图：zhangchenglin.top

**Comment by seriouszyx** [comment]
> @Dawn2019
> 老哥，可以用豆瓣插件来添加图书/电影/游戏的哦，我是按那个插件搞得，你可以看一下效果图：zhangchenglin.top

之前见过那个插件，效果挺不错的。

不过我是着重记一下当时看完的感受，过后一段时间还可能会修改，豆瓣的好像是评论后就不能修改了；还有我是计划着这个页面一年后再重新清空，对比记录一下每年阅读的进步，再者自己写样式也比较随意一点。

最后还是非常感谢你的推荐 :heart:

**Comment by Dawn2019** [comment]
> @seriouszyx
> > @Dawn2019
> > 老哥，可以用豆瓣插件来添加图书/电影/游戏的哦，我是按那个插件搞得，你可以看一下效果图：zhangchenglin.top
> 
> 之前见过那个插件，效果挺不错的。
> 
> 不过我是着重记一下当时看完的感受，过后一段时间还可能会修改，豆瓣的好像是评论后就不能修改了；还有我是计划着这个页面一年后再重新清空，对比记录一下每年阅读的进步，再者自己写样式也比较随意一点。
> 
> 最后还是非常感谢你的推荐 :heart:


> @seriouszyx
> > @Dawn2019
> > 老哥，可以用豆瓣插件来添加图书/电影/游戏的哦，我是按那个插件搞得，你可以看一下效果图：zhangchenglin.top
> 
> 之前见过那个插件，效果挺不错的。
> 
> 不过我是着重记一下当时看完的感受，过后一段时间还可能会修改，豆瓣的好像是评论后就不能修改了；还有我是计划着这个页面一年后再重新清空，对比记录一下每年阅读的进步，再者自己写样式也比较随意一点。
> 
> 最后还是非常感谢你的推荐 :heart:

嗯啊~
