### ISSUE TITLE
【通天塔之Vue】壹 缘起-乾坤大挪移 | 隐秀 | seriouszyx

### ISSUE THREAD

**Issue by seriouszyx** [seriouszyx/seriouszyx.github.io#28]
https://seriouszyx.github.io/2019/04/29/%E3%80%90%E9%80%9A%E5%A4%A9%E5%A1%94%E4%B9%8BVue%E3%80%91%E5%A3%B9-%E7%BC%98%E8%B5%B7-%E4%B9%BE%E5%9D%A4%E5%A4%A7%E6%8C%AA%E7%A7%BB.html

**Comment by LixandR** [comment]
vue确实用着爽
