### ISSUE TITLE
Assignment #2: Breakout | 隐秀 | seriouszyx

### ISSUE THREAD

**Issue by seriouszyx** [seriouszyx/seriouszyx.github.io#9]
https://seriouszyx.github.io/2019/03/17/Assignment-2-Breakout.html 

 简答 Java支持的数据类型有哪些？什么是自动拆装箱？ 接口和抽象类的区别是什么？ String s = new String(“abc”); 创建了几个对象？为什么？  Console Programming这部分的题没有 starter codes，自己创建。 移动零给定一个数组 nums，编写一个函数将所有 0 移动到数组的末尾，同时保持非零元素的相对顺序。  样例输入: [0,1,0,3,

**Comment by hyw-zero** [comment]
膜拜
